apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: sparenajob
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  schedule: "0 5,9,13,19 * * *"
  resources:
    requests:
      cpu: 400m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1Gi
  restartPolicy: Never
  kafka:
    pool: nav-prod
  vault:
    enabled: true
  env:
    - name: MOUNT_PATH_VAULT
      value: "/postgresql/prod-fss"
    - name: SPARENAPROXY_DB_URL
      value: "jdbc:postgresql://A01DBVL014.adeo.no:5432/sparenaproxy"