apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: sparenajob
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  schedule: "0 5,9,13,19 * * *"
  resources:
    requests:
      cpu: 400m
      memory: 768Mi
    limits:
      cpu: 500m
      memory: 1Gi
  restartPolicy: Never
  kafka:
    pool: nav-prod
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  envFrom:
    - secret: google-sql-sparenaproxy-sparenaproxy-sparenajob-4a490ebc
  env:
    - name: CLOUD_SQL_INSTANCE
      value: teamsykmelding-prod-2acd:europe-north1:sparenaproxy-db-instance